#!/usr/bin/env bash
cd MohaMeD
echo -e "\e[33m
echo -e "\e[33m    _   _   _                            \e[0m"
echo -e "\e[33m   |  \/  |  _| |_| |_| |                   \e[0m"
echo -e "\e[33m   | |\/| |/ _`   |   |   | '_ \ / _ \ \ /\ / / \e[0m"
echo -e "\e[33m   | |  | | (_| | |_| |_| | | |  /\ V  V /     \e[0m"
echo -e "\e[33m   |_|  |_|\__,_|\__|\__|_| |_|\___| \_/\_/   \e[0m"
echo -e "\e[33m                                           \e[0m"                                 
while(true) do
lua start.lua 
done
