#!/usr/bin/env bash
cd SNIEBR
echo -e "\e[33m        ____          _      _    \e[0m"
echo -e "\e[33m       / ___|   _ __ (_) ___| |__  _ __         \e[0m"
echo -e "\e[33m       \__ __\ | '_ \| |/ _ \ '_ \| '__|     \e[0m"
echo -e "\e[33m         ___)  | | | | || __/ |_) | |    \e[0m"
echo -e "\e[33m        |___/|_| |_|_|\___|_.__/  |_|   \e[0m"
echo -e "\e[33m       ______________________________  \e[0m"
echo -e "\e[33m        تم تنصيب سورس سنايبر شكرا لستخدامك السورس   \e[0m"
while(true) do
lua start.lua 
done
