#!/usr/bin/env bash
cd Tshake
echo -e "\e[33m           \e[0m"
echo -e "\e[33m           \e[0m"
echo -e "\e[33m           \e[0m"
echo -e "\e[33m           \e[0m"
echo -e "\e[33m           \e[0m"
while(true) do
lua start.lua 
done
